import localFont from "next/font/local";
import "./globals.css";
import NextAuthProvider from "./providers/NextAuthProvider";
import { GlobalStoreProvider } from "../context/GlobalStoreContext";
import dynamic from "next/dynamic";

export const metadata = {
    title: "Recording",
    description: "Generated by create next app",
};

const myFont = localFont({
    src: "../../public/fonts/Motiva-Sans-Light.ttf",
    display: "swap",
    variable: "--font-motiva-light",
});

const myFontBold = localFont({
    src: "../../public/fonts/Motiva-Sans-Bold.ttf",
    display: "swap",
    variable: "--font-motiva-bold",
});

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={` ${myFontBold.variable} ${myFont.variable} bg-main text-[#18216D]`}
            >
                <NextAuthProvider>
                    <GlobalStoreProvider>
                        {children}
                    </GlobalStoreProvider>
                </NextAuthProvider>
            </body>
        </html>
    );
}
